apiVersion: v1
kind: Service
metadata:
  name: express-service
  labels:
    app:  mongodb-express
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30021
  selector:
    app:  mongodb-express